### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by MED-P0520** [broadinstitute/gnomad-browser#1054]
Stack trace:
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at hu (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:365287)
    at gl (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:378458)
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:479427)
    at Vo (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:323755)
    at yl (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:376318)
    at rl (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:372472)
    at https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:324046
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:479427)
    at Vo (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:323755)
    at Ko (https://gnomad.broadinstitute.org/js/bundle-7af6653ae8e1da79ae84.js:2:323991)
```

Route: /gene/ENSG00000113140?dataset=gnomad_r2_1

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35

**Comment by rileyhgrant** [comment]
I'm currently unable to replicate this when I go to

https://gnomad.broadinstitute.org/gene/ENSG00000113140?dataset=gnomad_r2_1

Is this a recurring problem for you @MED-P0520, and/or did you do anything in particular when on that Gene page that gave this error/issue?

**Comment by rileyhgrant** [comment]
This issue is unable to be replicated, and appears to not be an ongoing thing. As such, this issue is being closed.
