### ISSUE TITLE
Cannot read properties of null (reading 'data')

### ISSUE THREAD

**Issue by thudaniel2333** [broadinstitute/gnomad-browser#1096]
Stack trace:
```
TypeError: Cannot read properties of null (reading 'data')
    at https://gnomad.broadinstitute.org/js/904-aba495e171d30b1d29cf.js:55:584
    at Array.map (<anonymous>)
    at https://gnomad.broadinstitute.org/js/904-aba495e171d30b1d29cf.js:55:549
    at au (https://gnomad.broadinstitute.org/js/bundle-e7732344dfdac16dfb25.js:39:197340)
    at wl (https://gnomad.broadinstitute.org/js/bundle-e7732344dfdac16dfb25.js:39:216138)
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-e7732344dfdac16dfb25.js:39:314904)
    at Vo (https://gnomad.broadinstitute.org/js/bundle-e7732344dfdac16dfb25.js:39:159232)
    at bl (https://gnomad.broadinstitute.org/js/bundle-e7732344dfdac16dfb25.js:39:215897)
    at https://gnomad.broadinstitute.org/js/bundle-e7732344dfdac16dfb25.js:39:215808
    at L (https://gnomad.broadinstitute.org/js/bundle-e7732344dfdac16dfb25.js:39:313843)
```

Route: /downloads

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**Comment by rileyhgrant** [comment]
Hiya, thanks for filing this issue. I cannot currently replicate this, do you have any additional info as to when this occurred?

Navigating to https://gnomad.broadinstitute.org/downloads and scrolling up and down the page, my browser appears stable on Firefox, Chrome, and Safari.

**Comment by rileyhgrant** [comment]
Closing this issue as it's not reproducible.

Our best guess as to this particular case is that were loading the downloads page of the browser at pretty much exactly the time that a blue/green deployment switch was happening. These, while near instant, do have a very brief window of time in which errors like this will occur.
