### ISSUE TITLE
Cannot read properties of null (reading 'data')

### ISSUE THREAD

**Issue by zhenghl2** [broadinstitute/gnomad-browser#1195]
Stack trace:
```
TypeError: Cannot read properties of null (reading 'data')
    at https://gnomad.broadinstitute.org/js/904-99427c8429cfc249024d.js:55:584
    at Array.map (<anonymous>)
    at https://gnomad.broadinstitute.org/js/904-99427c8429cfc249024d.js:55:549
    at au (https://gnomad.broadinstitute.org/js/bundle-bf66715f3dfe0a7d6530.js:39:197340)
    at wl (https://gnomad.broadinstitute.org/js/bundle-bf66715f3dfe0a7d6530.js:39:216138)
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-bf66715f3dfe0a7d6530.js:39:314904)
    at Vo (https://gnomad.broadinstitute.org/js/bundle-bf66715f3dfe0a7d6530.js:39:159232)
    at bl (https://gnomad.broadinstitute.org/js/bundle-bf66715f3dfe0a7d6530.js:39:215897)
    at https://gnomad.broadinstitute.org/js/bundle-bf66715f3dfe0a7d6530.js:39:215808
    at L (https://gnomad.broadinstitute.org/js/bundle-bf66715f3dfe0a7d6530.js:39:313843)
```

Route: /downloads

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by rileyhgrant** [comment]
Closing this issue due to inactivity and irreproducibility.
