### ISSUE TITLE
Cannot read properties of undefined (reading 'isV4')

### ISSUE THREAD

**Issue by FlorianErger** [broadinstitute/gnomad-browser#1256]
Dear gnomAD team,

when trying to access variants on the mitochondrial genome, I get the below error trace. I was previously able to access mitochondrial variants in the gnomAD v3 dataset. The same happens in the region view when querying mitochondrial regions by coordinate. For a split second, the data seems to display in the browser before the page is replaced by the generic error page.

Thanks and best wishes,
Florian

Stack trace:
```
TypeError: Cannot read properties of undefined (reading 'isV4')
    at D (https://gnomad.broadinstitute.org/js/601-5dfcd93ca4ac1ebf1898.js:18:10922)
    at F (https://gnomad.broadinstitute.org/js/601-5dfcd93ca4ac1ebf1898.js:18:11601)
    at new v (https://gnomad.broadinstitute.org/js/759-cff24fb076901e1a6791.js:270:100)
    at wi (https://gnomad.broadinstitute.org/js/bundle-8fbad1c54f205d6d843d.js:39:163860)
    at za (https://gnomad.broadinstitute.org/js/bundle-8fbad1c54f205d6d843d.js:39:181278)
    at wu (https://gnomad.broadinstitute.org/js/bundle-8fbad1c54f205d6d843d.js:39:219320)
    at dl (https://gnomad.broadinstitute.org/js/bundle-8fbad1c54f205d6d843d.js:39:210795)
    at fl (https://gnomad.broadinstitute.org/js/bundle-8fbad1c54f205d6d843d.js:39:210720)
    at rl (https://gnomad.broadinstitute.org/js/bundle-8fbad1c54f205d6d843d.js:39:207750)
    at https://gnomad.broadinstitute.org/js/bundle-8fbad1c54f205d6d843d.js:39:159523
```

Route: /gene/ENSG00000198899?dataset=gnomad_r3

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46

**Comment by rileyhgrant** [comment]
Hey @FlorianErger 

Thanks for filing this issue! We'll get this fixed ASAP -- this seems like a very impactful regression we accidentally introduced.

Thanks for your patience!
