### ISSUE TITLE
Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by LiviaMoura** [broadinstitute/gnomad-browser#1380]
**Description**: Checking variant info

**Error message**: Cannot read properties of null (reading 'map')

**Stack trace**:
```
TypeError: Cannot read properties of null (reading 'map')
    at Z (https://gnomad.broadinstitute.org/js/326-76f749083ae39bff05f7.js:21:7278)
    at Yi (https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:172114)
    at wu (https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:218019)
    at pl (https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:210795)
    at fl (https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:210720)
    at rl (https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:207750)
    at https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:159523
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:314904)
    at Vo (https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:159232)
    at Ko (https://gnomad.broadinstitute.org/js/bundle-71d3c7d3a1e0c7bce8b2.js:39:159468)
```

**Route**: /variant/GD_22Q11.2-AD__DEL?dataset=gnomad_sv_r4

**Browser**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by rileyhgrant** [comment]
In my console I additionally get:
```
TypeError: e.evidence is null
    Z StructuralVariantAttributeList.tsx:236
    React 6
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    loadData Query.tsx:115
```

**Comment by rileyhgrant** [comment]
@phildarnowsky-broad 

As mentioned in browser meeting assigning this to you to look into. Thank you!

**Comment by phildarnowsky-broad** [comment]
Hi @LiviaMoura ,

This is fixed now, https://gnomad.broadinstitute.org/variant/GD_22Q11.2-AD__DEL?dataset=gnomad_sv_r4 now shows that variant as expected. Thanks again for bringing this to our attention!
