### ISSUE TITLE
Cannot read properties of undefined (reading 'exons')

### ISSUE THREAD

**Issue by Jangseokhui** [broadinstitute/gnomad-browser#1525]
**Description**: on the MYBPC3 gene page(gnomAD v4.1.0), click the 'Expand to all variants' button, and crash the page

**Error message**: Cannot read properties of undefined (reading 'exons')

**Stack trace**:
```
TypeError: Cannot read properties of undefined (reading 'exons')
    at T (https://gnomad.broadinstitute.org/js/972-0f01076c3cca278a3dd5.js:157:3641)
    at aa (https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:178930)
    at $u (https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:231023)
    at Il (https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:218302)
    at Cl (https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:218230)
    at Ol (https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:218093)
    at vl (https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:215080)
    at https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:164852
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:319258)
    at $o (https://gnomad.broadinstitute.org/js/bundle-41cfd6264b3744bcecbf.js:39:164629)
```

**Route**: /gene/ENSG00000134571?dataset=gnomad_r4

**Browser**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by rileyhgrant** [comment]
@Jangseokhui 

Thanks for reporting this issue! Apologies for the slow reply -- this is now fixed in prod.

https://gnomad.broadinstitute.org/gene/ENSG00000134571?dataset=gnomad_r4

Thanks for your patience
