### ISSUE TITLE
Cannot read properties of undefined (reading 'genes')

### ISSUE THREAD

**Issue by Amokelani** [broadinstitute/gnomad-browser#1594]
**Description**: open more genes that span the inversion

**Error message**: Cannot read properties of undefined (reading 'genes')

**Stack trace**:
```
TypeError: Cannot read properties of undefined (reading 'genes')
    at B.render (https://gnomad.broadinstitute.org/js/507-7fa9ad76ba42321615b2.js:84:949)
    at Va (https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:191477)
    at qa (https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:191276)
    at $u (https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:232079)
    at Il (https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:218302)
    at Cl (https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:218230)
    at Ol (https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:218093)
    at vl (https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:215080)
    at https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:164852
    at t.unstable_runWithPriority (https://gnomad.broadinstitute.org/js/bundle-2f209aada5a33e4e9a48.js:39:319258)
```

**Route**: /variant/INV_CHR2_22375FB3?dataset=gnomad_sv_r4

**Browser**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0

**Comment by rileyhgrant** [comment]
Hiya, thanks for filing this issue!

Just posting here with a link and a screenshot for future reference. One of the members of our team has this in their backlog currently, so it's on our radar.

https://gnomad.broadinstitute.org/variant/INV_CHR2_22375FB3?dataset=gnomad_sv_r4

![Screenshot 2024-07-23 at 09 43 48](https://github.com/user-attachments/assets/ac198974-c6a3-4685-ad1f-5e2cb8cb9cfa)

**Comment by phildarnowsky-broad** [comment]
Hello @Amokelani , this is now fixed in production and I've verified that clicking the "and 134 more" link now works as intended. Thanks for your patience and thanks again for bringing this to our attention.
