### ISSUE TITLE
Loading chunk 309 failed.(error: https://gnomad.broadinstitute.org/js/309-7b6ce7c6d3d25bc5bb02.js)

### ISSUE THREAD

**Issue by FransDam29** [broadinstitute/gnomad-browser#1654]
**Description**: 

**Error message**: Loading chunk 309 failed.
(error: https://gnomad.broadinstitute.org/js/309-7b6ce7c6d3d25bc5bb02.js)

**Stack trace**:
```
ChunkLoadError
    at Object.j (https://gnomad.broadinstitute.org/js/bundle-8e69132abd488f90cf21.js:39:374656)
    at https://gnomad.broadinstitute.org/js/bundle-8e69132abd488f90cf21.js:39:371989
    at Array.reduce (<anonymous>)
    at Function.e (https://gnomad.broadinstitute.org/js/bundle-8e69132abd488f90cf21.js:39:371954)
    at https://gnomad.broadinstitute.org/js/242-290aa51ff7dc07574a4b.js:1:4285
    at P (https://gnomad.broadinstitute.org/js/bundle-8e69132abd488f90cf21.js:39:311466)
    at $u (https://gnomad.broadinstitute.org/js/bundle-8e69132abd488f90cf21.js:39:231600)
    at Il (https://gnomad.broadinstitute.org/js/bundle-8e69132abd488f90cf21.js:39:218302)
    at Cl (https://gnomad.broadinstitute.org/js/bundle-8e69132abd488f90cf21.js:39:218230)
    at Ol (https://gnomad.broadinstitute.org/js/bundle-8e69132abd488f90cf21.js:39:218093)
```

**Route**: /region/21-32631618-32631618?dataset=gnomad_r4

**Browser**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

**Comment by rileyhgrant** [comment]
Hi @FransDam29 

Thanks for filing this issue. I've looked at the region you were trying to see, and was unable to replicate this. Based on the stack trace, this appears to have been a network related error that caused a specific js chunk to not load, likely due to network connectivity. 

Since this is a non-replicable, transient network related error, I'll be closing this issue.

Thanks!
Riley
