### ISSUE TITLE
Invalid variant ID

### ISSUE THREAD

**Issue by Ray-Saif** [broadinstitute/gnomad-browser#820]
Stack trace:
```
Error: Invalid variant ID
    at f (https://gnomad.broadinstitute.org/js/620-cc9793cdb16559071d9c.js:1:1236)
    at https://gnomad.broadinstitute.org/js/804-19a2784e8db9d101d37d.js:1:63630
    at Array.map (<anonymous>)
    at sn (https://gnomad.broadinstitute.org/js/804-19a2784e8db9d101d37d.js:1:63598)
    at Yi (https://gnomad.broadinstitute.org/js/bundle-b35ef0ab8ce0de98073e.js:2:386677)
    at wu (https://gnomad.broadinstitute.org/js/bundle-b35ef0ab8ce0de98073e.js:2:432706)
    at pl (https://gnomad.broadinstitute.org/js/bundle-b35ef0ab8ce0de98073e.js:2:425449)
    at fl (https://gnomad.broadinstitute.org/js/bundle-b35ef0ab8ce0de98073e.js:2:425374)
    at rl (https://gnomad.broadinstitute.org/js/bundle-b35ef0ab8ce0de98073e.js:2:422404)
    at https://gnomad.broadinstitute.org/js/bundle-b35ef0ab8ce0de98073e.js:2:374070
```

Route: /variant/7-142119946-G-A?dataset=gnomad_r2_1

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

**Comment by nawatts** [comment]
#821 is the root cause for this.

In the meantime, such invalid variant IDs are filtered out to avoid crashing the browser.
