### ISSUE TITLE
Docker compose for local Browser development fails

### ISSUE THREAD

**Issue by rileyhgrant** [broadinstitute/gnomad-browser#999]
Since the migration to TypeScript, usage of the previously created docker compose file intended for use in local browser development with:

```
./development/env.sh browser up
```

Fails with the error:
```
[+] Running 1/0
 ⠿ Container gnomad-browser-browser-1  Created                                                                                                             0.0s
Attaching to gnomad-browser-browser-1
gnomad-browser-browser-1  | /home/node/app/browser/build/buildHelp.ts:11
gnomad-browser-browser-1  | const sourceFilePaths = (subsectionName: string, filenamePattern: string) => {
gnomad-browser-browser-1  |                                        ^
gnomad-browser-browser-1  |
gnomad-browser-browser-1  | SyntaxError: Unexpected token ':'
gnomad-browser-browser-1  |     at wrapSafe (internal/modules/cjs/loader.js:979:16)
gnomad-browser-browser-1  |     at Module._compile (internal/modules/cjs/loader.js:1027:27)
gnomad-browser-browser-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
gnomad-browser-browser-1  |     at Module.load (internal/modules/cjs/loader.js:928:32)
gnomad-browser-browser-1  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
gnomad-browser-browser-1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
gnomad-browser-browser-1  |     at internal/main/run_main_module.js:17:47
gnomad-browser-browser-1 exited with code 1
```

**Comment by rileyhgrant** [comment]
This isn't particularly urgent imo, as there are other ways to develop the browser locally (`./start.sh` or `yarn start`). Posting as an issue because it is a thing that is broken right now.
